// Generated by gencpp from file motoman_msgs/WriteSingleIORequest.msg
// DO NOT EDIT!


#ifndef MOTOMAN_MSGS_MESSAGE_WRITESINGLEIOREQUEST_H
#define MOTOMAN_MSGS_MESSAGE_WRITESINGLEIOREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motoman_msgs
{
template <class ContainerAllocator>
struct WriteSingleIORequest_
{
  typedef WriteSingleIORequest_<ContainerAllocator> Type;

  WriteSingleIORequest_()
    : address(0)
    , value(0)  {
    }
  WriteSingleIORequest_(const ContainerAllocator& _alloc)
    : address(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef uint32_t _address_type;
  _address_type address;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const> ConstPtr;

}; // struct WriteSingleIORequest_

typedef ::motoman_msgs::WriteSingleIORequest_<std::allocator<void> > WriteSingleIORequest;

typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest > WriteSingleIORequestPtr;
typedef boost::shared_ptr< ::motoman_msgs::WriteSingleIORequest const> WriteSingleIORequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motoman_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'industrial_msgs': ['/home/anthony/yaskawa/src/industrial_core/industrial_msgs/msg'], 'motoman_msgs': ['/home/anthony/yaskawa/src/motoman/motoman_msgs/msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01af3c84d8b155b2e313c831de55f80d";
  }

  static const char* value(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01af3c84d8b155b2ULL;
  static const uint64_t static_value2 = 0xe313c831de55f80dULL;
};

template<class ContainerAllocator>
struct DataType< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motoman_msgs/WriteSingleIORequest";
  }

  static const char* value(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
uint32 address\n\
int32 value\n\
";
  }

  static const char* value(const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.address);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteSingleIORequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motoman_msgs::WriteSingleIORequest_<ContainerAllocator>& v)
  {
    s << indent << "address: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.address);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOMAN_MSGS_MESSAGE_WRITESINGLEIOREQUEST_H
