(cl:defpackage motoman_msgs-srv
  (:use )
  (:export
   "CMDJOINTTRAJECTORYEX"
   "<CMDJOINTTRAJECTORYEX-REQUEST>"
   "CMDJOINTTRAJECTORYEX-REQUEST"
   "<CMDJOINTTRAJECTORYEX-RESPONSE>"
   "CMDJOINTTRAJECTORYEX-RESPONSE"
   "READSINGLEIO"
   "<READSINGLEIO-REQUEST>"
   "READSINGLEIO-REQUEST"
   "<READSINGLEIO-RESPONSE>"
   "READSINGLEIO-RESPONSE"
   "WRITESINGLEIO"
   "<WRITESINGLEIO-REQUEST>"
   "WRITESINGLEIO-REQUEST"
   "<WRITESINGLEIO-RESPONSE>"
   "WRITESINGLEIO-RESPONSE"
  ))

